### PR TITLE
feat: add about page

### PR DESCRIPTION
**Pull request by bhajneet**
### Summary of PR
Add page for About Us

### Tests for unexpected behavior
- mobile / desktop

### CODE REVIEW

**Comment by saihaj** [comment]
We should use a long dash 
801A7D0F-62AE-427A-A899-35E5FC0DA457

**Comment by saihaj** [comment]
I think we should remove “name and mission” and replace “what is shabadOS”

**Comment by bhajneet** [comment]
> I think we should remove “name and mission” and replace “what is shabadOS”

**Review by saihaj — APPROVED** [review]
LGTM just need to get CI to pass

**Review by saihaj — APPROVED** [review]

**Pull request merged**
