### PR TITLE
feat: footer component

### PR DESCRIPTION
**Pull request by saihaj**
### Summary

- Create footer component as per mockup
- Refactor theme utils

### CODE REVIEW

**Comment by bhajneet** [comment]
Have you seen feather icons? I'm wondering if they might look better for the social media icons

**Comment by bhajneet** [comment]
Maybe this will help? https://www.npmjs.com/package/feather-icons

**Comment by bhajneet** [comment]
Also note the variable hover effect on desktop, blue and opaque black based on how close you hover to the center of hte icon

**Comment by saihaj** [comment]
> Also note the variable hover effect on desktop, blue and opaque black based on how close you hover to the center of hte icon

Any guidance on how to implement this?

**Comment by saihaj** [comment]
> Maybe this will help? https://www.npmjs.com/package/feather-icons

So I tried this out. All the icons have no fill by default, so using the svg and customizing that was easier.

**Review by bhajneet — APPROVED** [review]

**Pull request merged**
